"""initial

Revision ID: d8cd90ead460
Revises: 
Create Date: 2026-05-01 15:07:09.393124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd8cd90ead460'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'telegram_id',
               existing_type=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('admins', 'name',
               existing_type=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('admins', 'role',
               existing_type=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=255),
               existing_nullable=True,
               existing_server_default=sa.text("'admin'"))
    op.alter_column('chats', 'group_id',
               existing_type=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('chats', 'title',
               existing_type=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('chats', 'creo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('chats', 'shop_google',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('chats', 'shop_fb',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('chats', 'console',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('chats', 'apps',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('chats', 'affiliate_mp',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('chats', 'partner_mp',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('chats', 'media_mt',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('chats', 'media_mp',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('chats', 'partner_mt',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'user_id',
               existing_type=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'group_id',
               existing_type=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=mysql.MEDIUMTEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('users', 'language_code',
               existing_type=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('users', 'title_gruop',
               existing_type=mysql.MEDIUMTEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('users', 'link_group',
               existing_type=mysql.MEDIUMTEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'link_group',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    op.alter_column('users', 'title_gruop',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    op.alter_column('users', 'language_code',
               existing_type=sa.String(length=100),
               type_=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    op.alter_column('users', 'group_id',
               existing_type=sa.String(length=255),
               type_=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=255),
               type_=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
    op.alter_column('users', 'user_id',
               existing_type=sa.String(length=255),
               type_=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)
    op.alter_column('chats', 'partner_mt',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('chats', 'media_mp',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('chats', 'media_mt',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('chats', 'partner_mp',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('chats', 'affiliate_mp',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('chats', 'apps',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('chats', 'console',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('chats', 'shop_fb',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('chats', 'shop_google',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('chats', 'creo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('chats', 'title',
               existing_type=sa.String(length=255),
               type_=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
    op.alter_column('chats', 'group_id',
               existing_type=sa.String(length=255),
               type_=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)
    op.alter_column('admins', 'role',
               existing_type=sa.String(length=255),
               type_=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True,
               existing_server_default=sa.text("'admin'"))
    op.alter_column('admins', 'name',
               existing_type=sa.String(length=255),
               type_=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
    op.alter_column('admins', 'telegram_id',
               existing_type=sa.String(length=255),
               type_=mysql.CHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
